spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chapter7?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: zfy123456

# 注意注意
#mybatis.mapper-locations=classpath:mapper/*.xml        #这种方式需要自己在resources目录下创建mapper目录然后存放xml
mybatis:
  mapper-locations: classpath:com/vincent/springboot/study/mapper/*.xml
  type-aliases-package: com.vincent.springboot.study.entity
  configuration:
    map-underscore-to-camel-case: true
