server:
  port: 8081


person:
  lastName: vincent
  age: 20
  boos: true
  birth: 2018/12/12
  maps: {k1: v1, k2: v2}
  lists:
    - zhangsan
    - lisi
    - wangwu
    - zhaoliu
  dog:
    name: tom
    age: 12